name: GitHub Actions Fibonacci Workflow
on: 
  push

permissions: 
  contents: read
  id-token: write

jobs:
  Build-job:
      uses: jfgriffiths/workflow-template/.github/workflows/deploy-dotnet-az-func.yml@main
      with: 
        dotnet-version: '10.0.x'
        project-path: 'FibonacciService/FibonacciService/FibonacciService.csproj'
        function-name: 'svc-fibonacci'
        workflow-name: 'github-action-workflow'
        
