name: GitHub Actions Fibonacci Workflow
on: 
  push

permissions: 
  contents: read
  id-token: write

jobs:
  Build-job:
      uses: jfgriffiths/workflow-template/tree/main/.github/workflows/deploy-dotnet-az-func.yml
      with: 
        dotnet-version: 10.0x
        project-path: FibonacciService/FibonacciService/FibonacciService.csproj
        function-name: svc-fibonacci
        
